# Generated by Django 4.2.7 on 2025-03-24 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0018_remove_accel_data_accel_x_accel_y_accel_z'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('HS1', 'HS1'), ('HS2', 'HS2'), ('HS3', 'HS3'), ('HS4', 'HS4')], max_length=5)),
                ('axis', models.CharField(choices=[('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=1)),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '   HS: Accel Data',
            },
        ),
        migrations.CreateModel(
            name='BearBoardTempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': ' Bear 1: Board Temperature Data',
            },
        ),
        migrations.CreateModel(
            name='CurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': ' Bear 1: Current Data',
            },
        ),
        migrations.CreateModel(
            name='GasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '    FC: Gas Data',
            },
        ),
        migrations.CreateModel(
            name='GyroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('HS1', 'HS1'), ('HS2', 'HS2'), ('HS3', 'HS3'), ('HS4', 'HS4')], max_length=5)),
                ('axis', models.CharField(choices=[('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=1)),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '   HS: Gyro Data',
            },
        ),
        migrations.CreateModel(
            name='HallVelocityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': ' Bear 1: Hall Velocity Data',
            },
        ),
        migrations.CreateModel(
            name='MotorTempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': ' Bear 1: Motor Temperature Data',
            },
        ),
        migrations.CreateModel(
            name='MotorTorqueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': ' Bear 1: Torque Data',
            },
        ),
        migrations.CreateModel(
            name='PowerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('Joule_H', 'Joule_H'), ('Joule_L', 'Joule_L')], max_length=7)),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '    Joule: Power Data',
            },
        ),
        migrations.CreateModel(
            name='PressureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('HS1', 'HS1'), ('HS2', 'HS2'), ('HS3', 'HS3'), ('HS4', 'HS4')], max_length=5)),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '   HS: Pressure Data',
            },
        ),
        migrations.CreateModel(
            name='TorqueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('HS1', 'HS1'), ('HS2', 'HS2'), ('HS3', 'HS3'), ('HS4', 'HS4')], max_length=5)),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '   HS: Torque Data',
            },
        ),
        migrations.CreateModel(
            name='UIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('data', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.trip')),
            ],
            options={
                'verbose_name_plural': '  UI: Data',
            },
        ),
        migrations.RemoveField(
            model_name='blinker',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='cruisedata',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='gyro_x',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='gyro_y',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='gyro_z',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='m_error_statusdata',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='magnetometer',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='meter_countdata',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='motor_statedata',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='rpmdata',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='throttledata',
            name='trip',
        ),
        migrations.AlterModelOptions(
            name='brakedata',
            options={'verbose_name_plural': '    FC: Brake Data'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '     Location Data'},
        ),
        migrations.AlterModelOptions(
            name='speeddata',
            options={'verbose_name_plural': '     Speed Data'},
        ),
        migrations.DeleteModel(
            name='Accel',
        ),
        migrations.DeleteModel(
            name='Blinker',
        ),
        migrations.DeleteModel(
            name='CruiseData',
        ),
        migrations.DeleteModel(
            name='Gyro_x',
        ),
        migrations.DeleteModel(
            name='Gyro_y',
        ),
        migrations.DeleteModel(
            name='Gyro_z',
        ),
        migrations.DeleteModel(
            name='M_Error_StatusData',
        ),
        migrations.DeleteModel(
            name='Magnetometer',
        ),
        migrations.DeleteModel(
            name='Meter_CountData',
        ),
        migrations.DeleteModel(
            name='Motor_StateData',
        ),
        migrations.DeleteModel(
            name='RPMData',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.DeleteModel(
            name='ThrottleData',
        ),
    ]
