# Generated by Django 4.2.7 on 2025-05-07 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0019_acceldata_bearboardtempdata_currentdata_gasdata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '     DAQ: Location Data'},
        ),
        migrations.AlterModelOptions(
            name='speeddata',
            options={'verbose_name_plural': '     DAQ: Speed Data'},
        ),
        migrations.AlterField(
            model_name='trip',
            name='stop',
            field=models.DateTimeField(blank=datetime.datetime(1970, 1, 1, 0, 0), default=datetime.datetime(1970, 1, 1, 0, 0), null=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
