name: Custom Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Extract branch name and sanitize
      id: extract_branch
      run: |
        # Get branch name from full ref
        ref=${{ github.ref }}
        branch=${ref#refs/heads/}
        # Replace slashes with dashes for a valid Docker tag
        tag=$(echo "$branch" | tr '/' '-')
        echo "branch=$branch" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/homework-website
        docker build -t $IMAGE_ID:${{ steps.extract_branch.outputs.tag }} .

    - name: Push Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/homework-website
        docker push $IMAGE_ID:${{ steps.extract_branch.outputs.tag }}
